### ISSUE TITLE
Schedule is squashed

### ISSUE THREAD

**Issue by ghickman** [PyconUK/2023.pyconuk.org#74] opened 2023-09-15 09:58 UTC
When viewing the shedule all the text is, for lack of a better word, squashed:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/2NuWKeo9/1da4350f-18ca-4a29-9268-5014c2834c95.jpg?v=fa817fcdac9f8f2ceb9e4fe5ec3716e1)

I've tested this in Firefox, Safari, and Chrome.

There also seems to be an offset from the right-hand edge of the page which you can see in the screenshot above.  This increases if I resize my browser.

**Comment by geokala** [comment] 2023-09-15 16:18
Hmm... playing with browser width (using firefox on ubuntu), I'm not seeing this behaviour.

**Comment by geokala** [comment] 2023-09-15 16:18
@ghickman Do you see the same behaviour on pretix itself if you click through?

**Comment by geokala** [comment] 2023-09-15 16:18
(link: https://pretalx.com/pyconuk-2023/schedule/ )

**Comment by BjarniRunar** [comment] 2023-09-15 19:54
Hi! This is my fault.

If your screen/window is small enough, it IS squashed.

This is to try and avoid side-scrolling, because that was causing parts of the schedule to be invisible - people literally didn't know there were events happening. There are limits in the code as to how much we squash it, and if people thing it's too much (and prefer side scrolling) they can be adjusted. It never squashes more than it needs to though.

**Comment by BjarniRunar** [comment] 2023-09-15 19:55
And getting it to line up perfectly was beyond my capabilities, if I got it just right in Firefox it was wrong in Chromium, and vice versa, so yes, there is also an irregular amount of wasted space around the edges. IMO this is practicality/usability trumping aesthetics, but if others want to tip the scales in another direction I'll understand.

**Comment by geokala** [comment] 2023-09-16 10:42
@ghickman @BjarniRunar Ah, I see- I still can't reproduce on my desktop no matter what resizing or refreshing I've tried, but managed to on my phone. I'll have a little play with the max resizing on a PR and see if there's a minor tweak that can avoid it compressing, but yeah- it does feel like we're very much into "I wonder how THIS browser will decide to play today" territory.

**Comment by geokala** [comment] 2023-09-16 10:55
If either of you are interested to check whether this fixes the issue (or introduces other ones for either of you):
https://deploy-preview-75--unique-dragon-f0bac4.netlify.app/schedule/
(based off PR https://github.com/PyconUK/2023.pyconuk.org/pull/75 - it applies the same transform+scale to Y as to X so I /think/ it should fix the compression- and indeed it looks like it does avoid the compression, but also it appears to not fully apply the resize on my phone)

**Comment by geokala** [comment] 2023-09-17 10:42
@ghickman I believe the thing I just merged should sort the issue. I'll mark this as closed, but feel free to reopen if you're still experiencing problems (after clearing cache/etc, but you probably know the drill).

**Closed by geokala** 2023-09-17 10:42 UTC

**Comment by ghickman** [comment] 2023-09-18 08:14
Hi both, thanks for digging into this. The squashed effect is indeed gone with your changes @geokala 🎉  

> Are you using a particularly wide or narrow display?

I'm using a 27" display, with my browser window set to 1420x640px, at full width it's 2560x640px.

> This is to try and avoid side-scrolling, because that was causing parts of the schedule to be invisible - people literally didn't know there were events happening

Completely understandable!

> Do you see the same behaviour on pretix itself if you click through?

I don't, and it's clear there are further rooms on the schedule when viewing it there.

Not to undermine either of y'alls hard work here (it really is appreciated, this is a hard problem, so thank you for trying to fix it!),  would it be simpler to promote the link to pretalx who already deal with all screen sizes, and save yourselves some time playing whack-a-mole with an embedded element?  Just an idea, please feel free to ignore it 🙂

**Comment by BjarniRunar** [comment] 2023-09-18 16:24
Pretalx also requires side-scrolling, so it has the exact same usability issues. That's no surprise - it's their embedded widget that was failing to scale down in the first place.

Possibly the right thing would be to propose/contribute some fixes upstream. But our case is special, in that we hit a sweet spot where the schedule is small enough that scaling down is feasible, but also large enough that scaling down is worth doing. Many events are probably either small enough that this doesn't come up, or so large that scaling down would make things totally unreadable.

It's just a hard problem to solve in the general case, so custom per-event tweaks like this may actually be the best case.

**Comment by geokala** [comment] 2023-09-19 16:37
Yeah- I did consider contacting pretalx themselves, but it does seem like something that'd be a lot of effort for them with, as @BjarniRunar notes, likely infrequent reward (and lots of issues), so... yeah.

Embedding the elements is new this year, and intended to make it a bit quicker in general for people to see the information (which it's hopefully doing- of course, nobody raises issues to say "This is so much quicker and easier to use than it was before", so it's hard to tell!).

So, for the moment I think we'll be happy that it's probably working, or at least not annoying enough for anyone else to figure out how to complain, and see if that changes in future!
